name: Laravel CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, sqlite, bcmath
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --no-interaction

      - name: Copy .env
        run: cp .env.example .env

      - name: Generate app key
        run: php artisan key:generate

      - name: Prepare SQLite database file
        run: mkdir -p database && touch database/database.sqlite

      - name: Run migrations
        run: php artisan migrate --force

      # If any tests or pages expect demo rows, uncomment:
      # - name: Seed database
      #   run: php artisan db:seed --force

      - name: Run tests
        run: php artisan test --without-tty --no-interaction
